[project]
name = "rabbit-wrapper"
version = "0.3"
dependencies = [
    "pika",
    "msgpack",
    "fastapi"
]

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests"]
namespaces = false

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
