[project]
name = "rabbit_wrapper"
version = "0.1"
dependencies = [
    "pika==1.3.2",
    "msgpack==1.0.7"
]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"