[project]
name = "rabbit-wrapper"
version = "0.3.7"
dependencies = [
    "pika",
    "msgpack",
    "fastapi"
]

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
