[project]
name = "rabbit-wrapper"
version = "0.3.3"
dependencies = [
    "pika",
    "msgpack",
    "fastapi"
]

[tool.setuptools.package-dir]
"" = "src"

[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"
